-- 20260912000000_fix_driver_onboarding.sql

-- 1. Structured Work Area
ALTER TABLE public.warehouses ADD COLUMN work_area TEXT;

UPDATE public.warehouses
SET work_area = 'Udupi'
WHERE name ILIKE '%udupi%' OR address ILIKE '%udupi%';

UPDATE public.warehouses
SET work_area = 'Manipal'
WHERE name ILIKE '%manipal%' OR address ILIKE '%manipal%';

-- 2. Training Content
ALTER TABLE public.driver_training_modules ADD COLUMN content TEXT;

UPDATE public.driver_training_modules
SET content = 'Driver assignments in FlashGO are fully automated through the backend system. 
- You must be approved and toggled ONLINE in the Driver App to receive assignments.
- The system assigns orders based on FEFO picking status, packer readiness, and driver proximity.
- Do NOT attempt to self-assign random customer orders. Wait for the assigned trip to appear in your Driver app dashboard.'
WHERE title = 'How Driver Assignments Work';

UPDATE public.driver_training_modules
SET content = 'Warehouse Handover is a strict process to maintain inventory accuracy:
- The Picker and Warehouse Staff will complete the Pick and Pack process.
- Do NOT take the order or leave the warehouse until the Warehouse Manager confirms the "handed_off" workflow on their screen.
- Only after successful handover confirmation in the system will the trip become active for delivery on your app.'
WHERE title = 'Warehouse Handover Process';

UPDATE public.driver_training_modules
SET content = 'Starting your delivery trip correctly ensures the customer is notified:
- Start only your assigned trip using the app button.
- The backend will automatically transition the order status and notify the customer.
- You take full responsibility for the order package once the trip starts.'
WHERE title = 'Starting a Delivery';

UPDATE public.driver_training_modules
SET content = 'Navigation and Live Tracking are essential for FlashGO operations:
- The app uses foreground location tracking to show customers your progress.
- Live location is only tracked while you are on an active trip.
- Follow the app''s navigation routes and ETA suggestions for maximum efficiency.'
WHERE title = 'Navigation & Location Tracking';

UPDATE public.driver_training_modules
SET content = 'Cash on Delivery (COD) requires careful handling:
- The exact COD amount required will be displayed in your Driver app, derived from the backend.
- You must collect the exact required amount from the customer.
- Never fake a paid state. You are liable for the cash collected during your shift and must deposit it at the warehouse.'
WHERE title = 'COD Handling';

UPDATE public.driver_training_modules
SET content = 'OTP Verification is a mandatory security step:
- You can only mark a delivery as complete if the customer provides the valid OTP generated by our backend.
- Never bypass the OTP check or mark an order delivered if the customer cannot provide the OTP or is unavailable.'
WHERE title = 'Delivery OTP Verification';

UPDATE public.driver_training_modules
SET content = 'Handling failed or cancelled deliveries correctly:
- If a customer is unavailable or cancels at the door, DO NOT mark the order as delivered.
- Use the app''s explicit failure/cancellation process.
- Return the exact package and inventory to the warehouse Manager to preserve system correctness.'
WHERE title = 'Failed / Cancelled Delivery Handling';

UPDATE public.driver_training_modules
SET content = 'Safety is our top priority:
- Practice safe riding and adhere to all traffic rules.
- Do not interact with your phone while the vehicle is moving.
- Secure the package properly before leaving the warehouse.'
WHERE title = 'Basic Delivery Safety';

-- 3. Strict RLS for Onboarding Status
-- Drop old permissive policies and recreate with strict status check
DROP POLICY IF EXISTS "Drivers can update their own onboarding" ON public.driver_onboarding;

-- Create policy that allows drivers to update onboarding ONLY IF they are NOT directly changing protected statuses
CREATE POLICY "Drivers can update their own onboarding"
    ON public.driver_onboarding FOR UPDATE
    USING (auth.uid() = id AND status IN ('in_progress', 'changes_requested'))
    WITH CHECK (auth.uid() = id AND (
      -- They cannot change the status manually to a protected state via direct UPDATE
      status IN ('in_progress', 'ready_to_submit', 'changes_requested')
    ));

-- 4. Server-Side Submission RPC
CREATE OR REPLACE FUNCTION public.submit_driver_application()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_onboarding RECORD;
    v_profile RECORD;
    v_warehouse RECORD;
    v_required_trainings INTEGER;
    v_completed_trainings INTEGER;
    v_uid UUID := auth.uid();
BEGIN
    IF v_uid IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    -- Fetch profile
    SELECT * INTO v_profile FROM public.profiles WHERE id = v_uid FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Profile not found';
    END IF;

    IF v_profile.role = 'driver' THEN
        RETURN jsonb_build_object('success', true, 'message', 'Already a driver');
    END IF;

    IF v_profile.requested_role != 'driver' THEN
        RAISE EXCEPTION 'Driver role not requested';
    END IF;

    -- Fetch onboarding
    SELECT * INTO v_onboarding FROM public.driver_onboarding WHERE id = v_uid FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Driver onboarding application not found';
    END IF;

    IF v_onboarding.status IN ('submitted', 'under_review', 'approved') THEN
        RETURN jsonb_build_object('success', true, 'message', 'Already submitted or approved');
    END IF;

    -- Verify fields
    IF v_onboarding.language_pref IS NULL THEN RAISE EXCEPTION 'Language preference missing'; END IF;
    IF v_onboarding.vehicle_type IS NULL THEN RAISE EXCEPTION 'Vehicle type missing'; END IF;
    IF v_onboarding.work_area IS NULL THEN RAISE EXCEPTION 'Work area missing'; END IF;
    IF v_onboarding.work_type IS NULL THEN RAISE EXCEPTION 'Work type missing'; END IF;
    IF v_onboarding.warehouse_id IS NULL THEN RAISE EXCEPTION 'Warehouse missing'; END IF;
    IF v_onboarding.selfie_url IS NULL THEN RAISE EXCEPTION 'Selfie missing'; END IF;

    -- Verify warehouse
    SELECT * INTO v_warehouse FROM public.warehouses WHERE id = v_onboarding.warehouse_id AND is_active = true;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Invalid or inactive warehouse';
    END IF;

    IF v_warehouse.work_area != v_onboarding.work_area THEN
        RAISE EXCEPTION 'Warehouse work area does not match selected work area';
    END IF;

    -- Verify related records
    IF NOT EXISTS (SELECT 1 FROM public.driver_payout_details WHERE driver_id = v_uid) THEN
        RAISE EXCEPTION 'Payout details missing';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.driver_nominee_details WHERE driver_id = v_uid) THEN
        RAISE EXCEPTION 'Nominee details missing';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM public.driver_agreement_acceptances WHERE driver_id = v_uid) THEN
        RAISE EXCEPTION 'Terms agreement missing';
    END IF;

    -- Verify training
    SELECT COUNT(*) INTO v_required_trainings FROM public.driver_training_modules WHERE is_active = true AND is_required = true;
    SELECT COUNT(*) INTO v_completed_trainings FROM public.driver_training_progress p JOIN public.driver_training_modules m ON p.module_id = m.id WHERE p.driver_id = v_uid AND m.is_active = true AND m.is_required = true;
    
    IF v_completed_trainings < v_required_trainings THEN
        RAISE EXCEPTION 'Mandatory training modules not completed';
    END IF;

    -- NOTE: Fee check goes here if a fee configuration is implemented in the future.

    -- Update onboarding status
    UPDATE public.driver_onboarding 
    SET status = 'submitted', submission_time = now() 
    WHERE id = v_uid;

    RETURN jsonb_build_object('success', true, 'message', 'Application submitted successfully');
END;
$$;

-- 5. Warehouse-Scoped Driver Approval
CREATE OR REPLACE FUNCTION public.approve_driver_application(p_driver_id uuid, p_action text, p_reason text DEFAULT NULL::text)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
    v_onboarding RECORD;
    v_profile RECORD;
    v_admin RECORD;
    v_existing_emp_id TEXT;
    v_required_trainings INTEGER;
    v_completed_trainings INTEGER;
BEGIN
    -- Verify admin caller
    SELECT * INTO v_admin FROM public.profiles WHERE id = auth.uid() AND role = 'admin';
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Unauthorized';
    END IF;

    IF p_driver_id = auth.uid() THEN
        RAISE EXCEPTION 'Cannot approve self';
    END IF;

    -- Lock and fetch onboarding record
    SELECT * INTO v_onboarding FROM public.driver_onboarding WHERE id = p_driver_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Driver onboarding application not found';
    END IF;

    -- Enforce Warehouse Manager Scope
    IF v_admin.warehouse_id IS NOT NULL THEN
        IF v_admin.warehouse_id != v_onboarding.warehouse_id THEN
            RAISE EXCEPTION 'Unauthorized: Warehouse scope mismatch';
        END IF;
    END IF;

    -- Lock and fetch profile
    SELECT * INTO v_profile FROM public.profiles WHERE id = p_driver_id FOR UPDATE;

    IF p_action = 'reject' THEN
        UPDATE public.driver_onboarding SET status = 'rejected', rejection_reason = p_reason WHERE id = p_driver_id;
        RETURN;
    END IF;

    IF p_action = 'request_changes' THEN
        UPDATE public.driver_onboarding SET status = 'changes_requested', rejection_reason = p_reason WHERE id = p_driver_id;
        RETURN;
    END IF;

    IF p_action = 'approve' THEN
        -- Verify mandatory fields
        IF v_onboarding.vehicle_type IS NULL OR v_onboarding.work_area IS NULL OR v_onboarding.warehouse_id IS NULL OR v_onboarding.selfie_url IS NULL THEN
            RAISE EXCEPTION 'Incomplete onboarding profile data';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM public.warehouses WHERE id = v_onboarding.warehouse_id AND is_active = true) THEN
            RAISE EXCEPTION 'Invalid or inactive warehouse';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM public.driver_payout_details WHERE driver_id = p_driver_id) THEN
            RAISE EXCEPTION 'Payout details missing';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM public.driver_nominee_details WHERE driver_id = p_driver_id) THEN
            RAISE EXCEPTION 'Nominee details missing';
        END IF;

        IF NOT EXISTS (SELECT 1 FROM public.driver_agreement_acceptances WHERE driver_id = p_driver_id) THEN
            RAISE EXCEPTION 'Terms agreement missing';
        END IF;

        -- Verify training
        SELECT COUNT(*) INTO v_required_trainings FROM public.driver_training_modules WHERE is_active = true AND is_required = true;
        SELECT COUNT(*) INTO v_completed_trainings FROM public.driver_training_progress p JOIN public.driver_training_modules m ON p.module_id = m.id WHERE p.driver_id = p_driver_id AND m.is_active = true AND m.is_required = true;
        
        IF v_completed_trainings < v_required_trainings THEN
            RAISE EXCEPTION 'Mandatory training modules not completed';
        END IF;

        -- Approval logic
        v_existing_emp_id := v_profile.employee_id;
        IF v_existing_emp_id IS NULL THEN
            v_existing_emp_id := 'EMP-' || nextval('public.staff_emp_seq');
        END IF;

        -- Update Profile
        UPDATE public.profiles 
        SET role = 'driver', 
            warehouse_id = v_onboarding.warehouse_id,
            employee_id = v_existing_emp_id,
            is_pending_staff = FALSE,
            requested_role = NULL
        WHERE id = p_driver_id;

        -- Update Onboarding Application
        UPDATE public.driver_onboarding SET status = 'approved', rejection_reason = NULL WHERE id = p_driver_id;

        PERFORM public.write_admin_audit_log(
            'DRIVER_VERIFIED_AND_APPROVED', 'profiles', p_driver_id::text, NULL,
            jsonb_build_object('role', v_profile.role, 'status', v_onboarding.status),
            jsonb_build_object('role', 'driver', 'warehouse_id', v_onboarding.warehouse_id, 'employee_id', v_existing_emp_id, 'status', 'approved'), NULL
        );
    ELSE
        RAISE EXCEPTION 'Invalid action';
    END IF;

END;
$function$;
